`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// tb_pc_stream — streaming testbench for line_buffer + pc_filter_core
//
// Purpose
// -------
// Every previous testbench presented a SINGLE patch with pixels_flat held
// static and valid_in driven continuously.  That combination cannot expose:
//
//   * pixel/tap desynchronisation (a static input survives any delay depth)
//   * valid-gap bugs (no gaps were ever generated)
//   * row-boundary bugs (only one patch, so no row wrap)
//
// This testbench streams a complete small image through the real line_buffer
// into pc_filter_core, exactly as the hardware does, and compares every output
// beat against a bit-exact reference generated by pc_golden.py.
//
// A 32x16 image wraps the row counter 16 times in a few hundred cycles, so
// row-boundary defects reproduce immediately instead of needing a full frame.
//
// Inputs (generated by gen_tb_vectors.py):
//   tb_stim.hex      IMG_W*IMG_H lines   input pixels
//   tb_expected.hex  N_OUT lines         expected filtered interior pixels
//   tb_thresh.hex    7 lines             Q2.14 thresholds
//
// On mismatch the testbench reports the output index, the centre pixel
// coordinates it corresponds to, expected vs actual, and the line_buffer
// counter state — enough to identify the failing cycle directly.
//////////////////////////////////////////////////////////////////////////////////

module tb_pc_stream;

// ── Image geometry — must match gen_tb_vectors.py ───────────────────────────
localparam IMG_W = 32;
localparam IMG_H = 16;
localparam N_IN  = IMG_W * IMG_H;
localparam N_OUT = (IMG_W - 6) * (IMG_H - 6);

localparam OUT_W = IMG_W - 6;   // output beats per row

// ── Vector files ────────────────────────────────────────────────────────────
localparam STIM_FILE = "E:/ELIM_NonSeparable_V2_0/vivado/fpga_pc/tb_stim.hex";
localparam EXP_FILE  = "E:/ELIM_NonSeparable_V2_0/vivado/fpga_pc/tb_expected.hex";
localparam THR_FILE  = "E:/ELIM_NonSeparable_V2_0/vivado/fpga_pc/tb_thresh.hex";

// ── Clock and reset ─────────────────────────────────────────────────────────
reg clk = 1'b0;
reg resetn = 1'b0;
always #5 clk = ~clk;          // 100 MHz

// ── Stimulus / expected storage ─────────────────────────────────────────────
reg [7:0]  stim [0:N_IN-1];
reg [7:0]  expd [0:N_OUT-1];
reg [15:0] thr  [0:6];

// ── DUT signals ─────────────────────────────────────────────────────────────
reg         valid_in;
reg  [7:0]  pixel_in;
wire [49*8-1:0] patch_flat;
wire        patch_valid;
wire [7:0]  pixel_out;
wire        valid_out;

// ── DUT: line_buffer -> pc_filter_core (same wiring as pc_axi.v) ────────────
line_buffer #(.MAX_W(1920)) u_lb (
    .clk        (clk),
    .resetn     (resetn),
    .valid_in   (valid_in),
    .pixel_in   (pixel_in),
    .img_width  (IMG_W[10:0]),
    .img_height (IMG_H[10:0]),
    .pixels_flat(patch_flat),
    .valid_out  (patch_valid)
);

pc_filter_core u_core (
    .clk        (clk),
    .resetn     (resetn),
    .valid_in   (patch_valid),
    .pixels_flat(patch_flat),
    .t0(thr[0]), .t1(thr[1]), .t2(thr[2]), .t3(thr[3]),
    .t4(thr[4]), .t5(thr[5]), .t6(thr[6]),
    .pixel_out  (pixel_out),
    .valid_out  (valid_out)
);

// ── Output collection and checking ──────────────────────────────────────────
integer out_idx  = 0;
integer errors   = 0;
integer reported = 0;
integer i;

// Per-column error tally — reveals edge-localised failures at a glance
integer col_err [0:1919];

// Snapshot of line_buffer state, captured when patch_valid fires, so that the
// state printed alongside a mismatch is the state that produced it.
localparam PIPE_DEPTH = 12;                 // pc_filter_core latency
reg [10:0] col_hist [0:PIPE_DEPTH];
reg [10:0] row_hist [0:PIPE_DEPTH];

always @(posedge clk) begin
    col_hist[0] <= u_lb.col_cnt;
    row_hist[0] <= u_lb.row_cnt;
    for (i = 1; i <= PIPE_DEPTH; i = i + 1) begin
        col_hist[i] <= col_hist[i-1];
        row_hist[i] <= row_hist[i-1];
    end
end

always @(posedge clk) begin
    if (resetn && valid_out) begin
        if (out_idx < N_OUT) begin
            if (pixel_out !== expd[out_idx]) begin
                errors = errors + 1;
                col_err[out_idx % OUT_W] = col_err[out_idx % OUT_W] + 1;
                if (reported < 20) begin
                    reported = reported + 1;
                    $display("MISMATCH #%0d  out_idx=%0d  centre=(row %0d, col %0d)  out_col=%0d",
                             reported, out_idx,
                             (out_idx / OUT_W) + 3, (out_idx % OUT_W) + 3,
                             out_idx % OUT_W);
                    $display("    expected=%0d  got=%0d  (t=%0t)",
                             expd[out_idx], pixel_out, $time);
                    $display("    lb counters now : col_cnt=%0d row_cnt=%0d",
                             u_lb.col_cnt, u_lb.row_cnt);
                    $display("    lb counters @%0d clks ago: col_cnt=%0d row_cnt=%0d",
                             PIPE_DEPTH, col_hist[PIPE_DEPTH], row_hist[PIPE_DEPTH]);
                    $display("    patch row0 = %0d %0d %0d %0d %0d %0d %0d",
                             u_lb.sr[0][0], u_lb.sr[0][1], u_lb.sr[0][2],
                             u_lb.sr[0][3], u_lb.sr[0][4], u_lb.sr[0][5],
                             u_lb.sr[0][6]);
                    $display("");
                end
            end
            out_idx = out_idx + 1;
        end else begin
            if (out_idx == N_OUT)
                $display("WARNING: extra output beat past N_OUT at t=%0t", $time);
            out_idx = out_idx + 1;
        end
    end
end

// ── line_buffer check: is the patch centre the expected pixel? ──────────────
integer lb_idx  = 0;
integer lb_err  = 0;
integer lb_rep  = 0;
integer exp_r, exp_c;

always @(posedge clk) begin
    if (resetn && patch_valid) begin
        exp_r = (lb_idx / OUT_W) + 3;
        exp_c = (lb_idx % OUT_W) + 3;
        if (u_lb.sr[3][3] !== stim[exp_r*IMG_W + exp_c]) begin
            lb_err = lb_err + 1;
            if (lb_rep < 12) begin
                lb_rep = lb_rep + 1;
                $display("LB #%0d beat=%0d  want centre(%0d,%0d)=%0d  sr[3][3]=%0d  col_cnt=%0d row_cnt=%0d",
                         lb_rep, lb_idx, exp_r, exp_c,
                         stim[exp_r*IMG_W + exp_c], u_lb.sr[3][3],
                         u_lb.col_cnt, u_lb.row_cnt);
            end
        end
        lb_idx = lb_idx + 1;
    end
end

// ── Main stimulus ───────────────────────────────────────────────────────────
integer p;

initial begin
    for (i = 0; i < 1920; i = i + 1) col_err[i] = 0;

    $readmemh(STIM_FILE, stim);
    $readmemh(EXP_FILE,  expd);
    $readmemh(THR_FILE,  thr);

    $display("========================================================");
    $display(" tb_pc_stream — streaming verification");
    $display("   image      : %0d x %0d", IMG_W, IMG_H);
    $display("   input beats: %0d", N_IN);
    $display("   expected   : %0d output beats (%0d x %0d)",
             N_OUT, IMG_H-6, OUT_W);
    $display("   thresholds : %0d %0d %0d %0d %0d %0d %0d",
             thr[0], thr[1], thr[2], thr[3], thr[4], thr[5], thr[6]);
    $display("========================================================");
    $display("");

    valid_in = 1'b0;
    pixel_in = 8'd0;
    resetn   = 1'b0;
    repeat (10) @(posedge clk);
    resetn   = 1'b1;
    repeat (4) @(posedge clk);

    // Stream the whole image, one pixel per clock, no gaps.
    for (p = 0; p < N_IN; p = p + 1) begin
        @(negedge clk);
        valid_in = 1'b1;
        pixel_in = stim[p];
    end

    @(negedge clk);
    valid_in = 1'b0;
    pixel_in = 8'd0;

    // Drain the pipeline
    repeat (40) @(posedge clk);

    // ── Report ──────────────────────────────────────────────────────────────
    $display("========================================================");
    $display(" RESULTS");
    $display("========================================================");
    $display("  output beats received : %0d  (expected %0d)", out_idx, N_OUT);
    $display("  mismatches            : %0d", errors);

    if (out_idx != N_OUT)
        $display("  *** BEAT COUNT WRONG — off by %0d ***", out_idx - N_OUT);

    if (errors == 0 && out_idx == N_OUT) begin
        $display("");
        $display("  PASS — bit-exact against pc_golden.py");
    end else begin
        $display("");
        $display("  Errors per output column:");
        for (i = 0; i < OUT_W; i = i + 1)
            if (col_err[i] != 0)
                $display("    out_col %0d (centre col %0d) : %0d errors  of %0d rows",
                         i, i + 3, col_err[i], IMG_H - 6);
        $display("");
        $display("  FAIL");
    end
    $display("  line_buffer beats     : %0d", lb_idx);
    $display("  line_buffer bad centres: %0d", lb_err);
    $display("========================================================");

    $finish;
end

// Safety net
initial begin
    #200000;
    $display("TIMEOUT");
    $finish;
end

endmodule
